### ISSUE TITLE
Brief API review

### ISSUE THREAD

**Issue by marius-mather** [Language-Research-Technology/ldaca-py#1]
Hi, just adding some initial thoughts after my first attempt to use the API. The example code I was given to access the Sydney Speaks data via the API worked fine.

Here, I'm trying to approach this API from the perspective of a user who has been
given the tool and is trying to work their way through it to get where they need to
go, rather than just being given some code they don't understand and running it.

I guess my main issue is that I would have no real idea how to navigate a collection
to find what I was interested in - I can't really see clear ways to navigate the
collection's structure/hierarchy to discover things like "oh, the files I want are 
DialogueText's with the type 'OrthographicTranscription'". I'm no expert in RO-Crate,
so I don't know how to find my way through one, and the API currently doesn't seem
to offer much help in that respect.

Some more code review oriented comments:

* Attributes like `ldaca.membership` don't seem to be very useful on their own - they only
  have values once you call methods like `get_members_of_collection()`.
  - Should this be a private attribute like `ldaca._membership`? And then `get_members_of_collection()` returns the value?
  - Should it be a property (using `@property`) so when you access `ldaca.membership` it's
    fetched on demand?
* It seems unpythonic to have methods like `get_collection()` return string messages
  like `"Saved in data"`. You can't do much with that return value. 
  Why not print these kinds of messages to the console, and either return
  a `True`/`False` for success, or the path to the file?
* Not sure why we first call `ldaca.store_data()` and then access `ldaca.pandas_dataframe`.
  Could the method just return the dataframe directly?
* For a user, it's hard to know what to do with `store_data()` when the signature is
  `store_data(self, *args, **kwargs):`. It would be nice if the signature specified
  which options were available. Methods like `get_collection()` have the same
  kind of signature.

**Comment by jnothman** [comment]
> It seems unpythonic to have methods like get_collection() return string messages
like "Saved in data".

Maybe "get" is the wrong verb, and it should be "retrieve" (but I agree about the return value). Failure would be best indicated by an exception. (it is exceptional.)
