### ISSUE TITLE
Updates to ldaca.py for oni-downloader

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/ldaca-py#2]
PT and I made some updates to a local version of ldaca.py so that the oni-downloader ran as expected. Could these updates be applied to the main version so that these will work when the oni-downloader is converted to a Jupyter notebook?

Adding the link to the sections of code below, followed by the updates to those lines:

https://github.com/Language-Research-Technology/ldaca-py/blob/9390b3609e608a0d38feaa517308ff441cc30d67/ldaca/ldaca.py#L280
`def download_file(self, url, file_path, DOWNLOAD_DIR=""):`

<br>

https://github.com/Language-Research-Technology/ldaca-py/blob/9390b3609e608a0d38feaa517308ff441cc30d67/ldaca/ldaca.py#L292
```
#ensure directory exists
download_path = os.path.join(DOWNLOAD_DIR, file_path)
dir = os.path.dirname(download_path)
if dir and not os.path.exists(dir):
    print("Creating directory:",dir)
    os.makedirs(dir)

with open(download_path, 'wb') as out_file:
```

<br>

https://github.com/Language-Research-Technology/ldaca-py/blob/9390b3609e608a0d38feaa517308ff441cc30d67/ldaca/ldaca.py#L296
`return download_path`

**Comment by moisbo** [comment]
For sure. Make a PR with this the same way you did oni-ui... same deal. Fork it, clone it, make a branch, run it in your computer, run the tests, and then PR
